phone_number: +1 234 567 89
support_email: support@mail.com
empty_path: javascript:void(0);
logo_medium: 96
logo_small: 64
url:
  placeholder:
    home_image: "https://via.placeholder.com/2000X1333//88929f/5a6270C/O https://placeholder.com/"
